### PR TITLE
get windows advertiser ID WP8

### PR DESCRIPTION
**Pull request by riccardo91**
get WAID throught Reflection if wp8 App run on wp8.1 OS

### CODE REVIEW

**Comment by hasjohnb** [comment]
Thanks for the contribution, @riccardo91 . We'll put this code in our dev repo, test it, and then copy back to this repo. So we may not merge this PR, but we'll pull in the code.

**Comment by riccardo91** [comment]
Hello @hasjohnb thank you for your reply!
Do you have any ETA? we need to run some CPI campaign with our customers in the next weeks

**Comment by john-gu** [comment]
Hi @riccardo91, we should be able to test and release by this week.

**Comment by riccardo91** [comment]
Thank you for the quick reply
just one more thing:
i don't know if this method return an empty string or a null value if advertiser ID is not enabled by user
(string) type.GetProperty("AdvertisingId").GetValue(null, null)
i think you need a null value to get everything works well

**Comment by john-gu** [comment]
@riccardo91 your call worked perfectly with both enabled and disabled advertiser ID. Thanks! We've merged and released the WP8 SDK with your update in version 3.4 which you can now download from the MAT platform.

**Comment by riccardo91** [comment]
Are you going to inform all wp8 customer about the new version?
Do you have any nuget package to import your library?

**Pull request closed without merging**
